apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-default
  name: spring-default
spec:
  selector:
    app: spring-default
  ports:
    - name: "default"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-default
  name: spring-default
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-default
  template:
    metadata:
      labels:
        app: spring-default
    spec:
      containers:
        - name: default
          image: spring-ingress-nginx:0.0.1-SNAPSHOT
          env:
            - name: JAVA_OPTS
              value: "-Xmx64m -Xms64m -XX:MaxDirectMemorySize=16M -XX:MaxMetaspaceSize=64M -XX:ReservedCodeCacheSize=16M -Xss256K"
            - name: BPL_JVM_THREAD_COUNT
              value: "32"
            - name: SPRING_PROFILES_ACTIVE
              value: default
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
